package com.reosrose.utildemo.utils;

/**
 * Created by yinsxi on 2018/1/17.
 */

public class ImageUrls {
    public static String [] imageUrls = {
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/bwKeUvrvGaXUDlIfXjA7OIuaQvWyf02ydcuY1mSJnGs!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RCck!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/j7O*mSNlxrEgCe3z33KQxAUTH1ojY9nDWPybc0P50jM!/b/dF4BAAAAAAAA&bo=OARUBgAPgBYRGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/S.S274ROOn7rO0dM0M3ufWRmMcD1rQNNUvYA3ATQSx8!/b/dFsBAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/9oYQx3RW9HkMl.cVOa2oCb3BuUbF2ll.BiZPTE8mk7M!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/iNCUHbvOVc60RCqd6a9MOxmrLZGbud4dJjARwFoWYn0!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/2vv**hNQyjQ1mzCAlo.L9Q*FQJ6zcRKPS65loZJjEWQ!/b/dPMAAAAAAAAA&bo=OASFBgAPLhcRGac!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/NQj4UTaxyBDNHZ*bc1Kj5Bp4jHqIGQJYofmpAWhJZWE!/b/dPMAAAAAAAAA&bo=6QU4BIAWDxARKUc!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/uu9AzgLvXbwJQYLniLNt59rc9*ImJf*6CyR2bhEJV8w!/b/dPMAAAAAAAAA&bo=WgY4BIAW8w4RGSU!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/L8rMiWStQm4Wr1Vzlqe8VJPxNzjeFMAB*8ltDB9WOvA!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/am.I6qgAfHsZX6Cw*Ce6AJfNliQOWx8rDr*SfxqTauQ!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/qcUTBbd0wXXWvSdNyeCUCDc9RNzSM4UBDO8iexG5Zy8!/b/dPIAAAAAAAAA&bo=OARUBgAPgBYRCck!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/XzHgmn7hdi2kAbLU9sTY0F3GSdrakpIsdbMY6y*aP90!/b/dD8BAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/*HsE*Nq0BINwXiBDZ3zmXd5F1CINA5vgQjwVqBR6fMc!/b/dF8BAAAAAAAA&bo=OARUBgAPgBYRCck!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/eI9M8FXIWVUM1yAGJVkDFnUKJVeypgWTmHww32KpNBs!/b/dD8BAAAAAAAA&bo=OARUBgAPgBYRKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/e0OUZZY9fVVhUWbhomKScuyv2n9b1*mJnIqA1YUPd60!/b/dPMAAAAAAAAA&bo=OARUBgAPgBYRKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/vRoYabljBoNJYIovHct17vWcXBBWmseOqhuNhh3ecQs!/b/dFsBAAAAAAAA&bo=VAY4BIAWAA8RCck!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/UjfizauspmBveq4EYSPf0JohG1xBcQSNHMMWLx6.V*Y!/b/dD8BAAAAAAAA&bo=OARUBgAPgBYRKek!&rf=viewer_4   ",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/ESppMQZrg*PLLRb111O3lU05is12bFcG7r8s*pQmJJ8!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/StJYwH1P76mWxLHXBpSS9OruLgtSq.lkuggNMcdqvMU!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8ROfk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/uETc0boZouVd38UBFkDENVwBNs82h4VCteeZF8qK9ZI!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/OtichLrsA32pkrpiCIPJW59NXBw7bzZ9EpNW2BT7gLs!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/e0OUZZY9fVVhUWbhomKScuyv2n9b1*mJnIqA1YUPd60!/b/dPMAAAAAAAAA&bo=OARUBgAPgBYRKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/eI9M8FXIWVUM1yAGJVkDFnUKJVeypgWTmHww32KpNBs!/b/dD8BAAAAAAAA&bo=OARUBgAPgBYRKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/WA4t5xoVLTwCetRX0aKHMsAjgcp.yM*0Sikbsuq3mKY!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/tfGQ5pzKUWG7asylhY.0iIn4ntT1uFBCQcK2pVPVlHk!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/zcXeWiYDCDUBD0Eph4mzAHKoaNVCg1xPMTHL6f28rFk!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/ZfGMT4cSX57anPjAdEGA3uBwjlOeLCgEmSqNFuC*wDA!/b/dGgBAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/aSWMprNbnguwoAiJJFqvLjE1LQNVgtLQN5HbUAEVYD4!/b/dPMAAAAAAAAA&bo=YAY4BIAW5A4RGQg!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/5pdI1.mmztx5put1sUcrjcLSge7k*TZHa8F0ngNZCxg!/b/dF8BAAAAAAAA&bo=KAY4BOMVAA8RGcU!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/35d7C4KuTS9AipHUXI.fG0RlMDcDTtpwt3vuOZasLKQ!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8ROfk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/N70qBmt9i2PCkKF59LiSM1LqkRSH6Vm3ByEhtp20O.U!/b/dGgBAAAAAAAA&bo=VAY4BIAWAA8ROfk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/pcyoFNvW*BpdcCKRN53sAym6zB4qHkvoekNVuhJ8hUU!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/JrFW.ehMfBQRtS5U.JyplXtRu63u7csVVCi5bwjxsss!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/8CNUFsG6CRxmww*MiVDwiuiOKXIeMBnzzIzrFr3yvFk!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/gkqKzUJUwd.EV3*GoKPHJ5wy4*m*WlkNCI2lso8N208!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/6Cf3XfSWScTEgv3cYlm7LTOecfd1qNIE5dSqf1M9ENg!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/DlhorXg8zSZIV9Oa8ILkHFYBaA4oD.Iju9s4HDtPZTA!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/cyIgdnsJLLfuFq6Fc3Bt7OeaARbuNdYvoMRTtwRO3ss!/b/dGgBAAAAAAAA&bo=VAY4BIAWAA8RKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/KJXFcJ64LKA8jagwP5xSN.Qg9y4DtVcm1qT32ncvSek!/b/dF4BAAAAAAAA&bo=OARUBgAPgBYRKek!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/ngz7PRogzRsByPh8m6n80uXm1qokw8Uv3mlDPTb9Nog!/b/dPMAAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/A5mNERd34XvJway1vTfn3zy*KtRvJeSugnZP0bkDLVw!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4 ",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/lNYdFlAwAimKq.RJfnRKoL0xWAT0.UbgRJmF9HINNAw!/b/dPIAAAAAAAAA&bo=OwY4BCgWAA8RGR4!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/N8foqO0RGrXMGH66KVWIZP4Pj1uSCaB5sU9IJLQKWZc!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/HTNcza4ce1l9Xnu.gfCe.UuXwIxVLgL7pudL.z7uGFs!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/TZiADhYscSbjK3WGKNu0zbLbNpv2TOj.yZ5Wadu6JF0!/b/dD8BAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/m7Y*ITyAUuU8XciRzXLSqjLOgYbUrPdyrajJXEx6SsU!/b/dFsBAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/GCMD*rgaVuINUP7P2S9DMz3qwevGRmtROclAnNoMPAw!/b/dPIAAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/.yRJyRU1DWCrUFLfe3rchaoeUAiEtJklS9ImKwjMa.o!/b/dF4BAAAAAAAA&bo=VAY4BIAWAA8RGdk!&rf=viewer_4",
            "http://m.qpic.cn/psb?/V11mmPKr18xmdk/iZgzLkd5K6*Ju8reO.45GB8jcFAf.aPUMw.7BL6KDfY!/b/dGUBAAAAAAAA&bo=VAY4BIAWAA8RCck!&rf=viewer_4http://m.qpic.cn/psb?/V11mmPKr18xmdk/iZgzLkd5K6*Ju8reO.45GB8jcFAf.aPUMw.7BL6KDfY!/b/dGUBAAAAAAAA&bo=VAY4BIAWAA8RCck!&rf=viewer_4",
    };
}
